# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: ur5e
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - ur16e_shoulder_pan_joint
    - ur16e_shoulder_lift_joint
    - ur16e_elbow_joint
    - ur16e_wrist_1_joint
    - ur16e_wrist_2_joint
    - ur16e_wrist_3_joint
    - _2finger_joint
    - ur5e_shoulder_pan_joint
    - ur5e_shoulder_lift_joint
    - ur5e_elbow_joint
    - ur5e_wrist_1_joint
    - ur5e_wrist_2_joint
    - ur5e_wrist_3_joint
    - finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ur5e/scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
  - name: ur16e/scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur16e_shoulder_pan_joint
      - ur16e_shoulder_lift_joint
      - ur16e_elbow_joint
      - ur16e_wrist_1_joint
      - ur16e_wrist_2_joint
      - ur16e_wrist_3_joint
  - name: ur5e_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      finger_joint